### PR TITLE
hamburger navbar | about us, home | new UI

### PR DESCRIPTION
**Pull request by akshay1027**
Fixes part one of #132

Have spent more than half a day on this! please let me know what should be the secondary colour so that I will change it! @abhijeet007rocks8 @DhairyaBahl 

screenshots:

ps: I have made hover effects as well!

### CODE REVIEW

**Comment by abhijeet007rocks8** [comment]
Does themobile  navbar changes colors with theme change

**Comment by DhairyaBahl** [comment]
@akshay1027 why the messages are still visible in the second image ? when the navbar covers the message. They shouldn't be visible because they must be behind the navbar ! Kindly fix that ^_^

**Comment by akshay1027** [comment]
@DhairyaBahl I have made them a bit transparent to differentiate from the top bar, if you want it to be opaque, I can do that!

**Comment by akshay1027** [comment]
> Does themobile navbar changes colors with theme change

yes!

**Comment by DhairyaBahl** [comment]
@akshay1027 It would be great if you can make that opaque asap. I will merge this PR right away ^_^

**Comment by akshay1027** [comment]
@DhairyaBahl I have made the required changes! Sorry was working on the About us page and completely forgot about this

**Review by DhairyaBahl — APPROVED** [review]
Okay then Everything seems perfect to me and I am squashing and merging this PR ^_^

**Comment by DhairyaBahl** [comment]
@akshay1027 thank you for the contribution !

**Pull request merged**
