### PR TITLE
solving reloading issue

### LINKED ISSUE #170: On routing different paths, the tab is reloading.
**Problem**
When we are clicking on the about us or home button on the homepage. The page is getting reload. But as we are using react Js for the frontend. We can prevent it from reloading.

**Expected behavior**
When we click on the about us or home button, only the path should change. And this should happen without reloading the page.

### LINKED ISSUE #173: Theme changes on page switch
When we click on about us page the default theme is not retained in about us page.

Try clicking the theme button on home and then go to about us page. It will still be in light theme whereas home is in dark theme

### PR DESCRIPTION
**Pull request by vivek80801**
This pull request will close #170  and  close #173 

Solving reloading issue. Thanks for merging my little contribution :sweat_smile:

### CODE REVIEW

**Comment by vivek80801** [comment]
This will also solve #173 
This pull request will also close #173

**Comment by abhijeet007rocks8** [comment]
@vivek80801 can you put here some scshots of iworking after issue  is solved

**Comment by vivek80801** [comment]
@abhijeet007rocks8  I am facing merge conflict while code from this code face. After I solved conflict. I can show you screen shots. 
Otherwise it will just wastage of time feel free to close pull request. Because it will cause conflict. I have no idea. How to solve conflict.

Thanks for your time

**Comment by abhijeet007rocks8** [comment]
If you are facing issue feel free to contact me. I can help you understand and this will come handy in future

**Review by abhijeet007rocks8 — CHANGES_REQUESTED** [review]
Fix Merge conflicts

**Comment by vivek80801** [comment]
@abhijeet007rocks8 How do I pull code from this codebase without losing my changes? New pull request is merged after my pull request in this codebase.

**Comment by DhairyaBahl** [comment]
@vivek80801 Kindly pull the new changes from the app.js.

**Comment by vivek80801** [comment]
I am closing this pull request. Because this pull request does not make any sense `App.js` has been already modified. This is a conflict. I have never solved merge conflicts and I have no idea. How to solve this merge conflict ?

Thanks for your valuable time :smile:

**Pull request closed without merging**
