### PR TITLE
Aboutus responsive

### PR DESCRIPTION
**Pull request by garvitgupta13**
fixed issue #492 
|      Before       |     After      |
| :-----------------: | :----------------: |
|image |image |

### CODE REVIEW

**Comment by garvitgupta13** [comment]
YES

**Comment by abhijeet007rocks8** [comment]
Merge conflict

**Comment by garvitgupta13** [comment]
> Merge conflict

resolved

**Comment by garvitgupta13** [comment]
@abhijeet007rocks8 merge conflict resolved please merge this PR

**Pull request merged**
