### PR TITLE
Auth routing setup

### PR DESCRIPTION
**Pull request by akshay1027**
Auth routing setup is done! 

partial fix of #161

### CODE REVIEW

**Comment by akshay1027** [comment]
check this out and let me know if you need any changes! @abhijeet007rocks8 @DhairyaBahl

**Comment by abhijeet007rocks8** [comment]
@akshay1027 There are merge conflicts Please resolve them.
If you face any issues to resolve them contact me.

Also login/signup should not be a separate identity it need to be invoked first them it would lead to messages

**Comment by akshay1027** [comment]
okay, I will try to change it!

**Comment by DhairyaBahl** [comment]
@akshay1027 resolve the conflicts and kindly tell me what is the status of the PR ?

**Comment by abhijeet007rocks8** [comment]
@akshay1027 Please resolve the merge conflicts so that we can merge the PR

**Comment by akshay1027** [comment]
conflicts resolved @abhijeet007rocks8 @DhairyaBahl

**Comment by akshay1027** [comment]
please check it out!

**Pull request closed without merging**
