### PR TITLE
enhanced the styling of scroll to bottom button for different themes

### PR DESCRIPTION
**Pull request by garvitgupta13**
fixed issue #490 
image
image

### CODE REVIEW

**Comment by garvitgupta13** [comment]
YES

**Comment by abhijeet007rocks8** [comment]
Merge conflict

**Comment by garvitgupta13** [comment]
> Merge conflict

resolved

**Comment by abhijeet007rocks8** [comment]
Still there

**Comment by garvitgupta13** [comment]
> Still there

resolved

**Comment by abhijeet007rocks8** [comment]
Do close the related issue

**Pull request merged**
