### PR TITLE
fixed css prefixes for cross browser compatibility

### LINKED ISSUE #240: Bug: Text in buttons of the welcome dialogue box becomes invisible on hovering
IMG_20210514_191409
I would like to fix this bug by making the text color remain the same even on hovering

### PR DESCRIPTION
**Pull request by N-Shar-ma**
## Fixes #240 

On pulling, I saw that a previous commit had already fixed the invisible text bug, however there was some css where the vendor prefixing needed fallbacks, and hence it was giving errors, so I have fixed that in this PR

### CODE REVIEW

**Comment by N-Shar-ma** [comment]
YES

**Comment by abhijeet007rocks8** [comment]
Please provide scshot of issue being fixed for reference

**Comment by N-Shar-ma** [comment]
> Please provide scshot of issue being fixed for reference

Sorry, this bugfix solves an error that showed up in the css code and it does not affect the visible output (on modern browsers at least!), so a screenshot is not possible

**Review by abhijeet007rocks8 — CHANGES_REQUESTED** [review]
Resolve the merge conflict please

**Comment by N-Shar-ma** [comment]
> Resolve the merge conflict please

Done!

**Review by abhijeet007rocks8 — APPROVED** [review]

**Pull request merged**
