### PR TITLE
Inputbox colour changed and border added

### PR DESCRIPTION
**Pull request by akshay1027**
Inputbox colour changed and border added to increase visibility.
Fixes: #144 

screenshots

### CODE REVIEW

**Comment by akshay1027** [comment]
please check these out @abhijeet007rocks8 @DhairyaBahl!

**Comment by abhijeet007rocks8** [comment]
Try a light color for dark theme and vice versa

**Comment by akshay1027** [comment]
I tried black doesn't look good in white theme @abhijeet007rocks8 imo

**Review by DhairyaBahl — APPROVED** [review]
Everything looks Good ! I am merging this PR

**Comment by DhairyaBahl** [comment]
Thanks for the contribution ^_^

**Pull request merged**
