### PR TITLE
Added feature to search text messages.

### LINKED ISSUE #757: add feature to search text message
@abhijeet007rocks8 Please assign

### PR DESCRIPTION
**Pull request by Shivangi-ch**
Fixes: #757

### CODE REVIEW

**Comment by Shivangi-ch** [comment]
YES

**Comment by Shivangi-ch** [comment]
@abhijeet007rocks8 Please review

**Comment by abhijeet007rocks8** [comment]
Merge conflict

**Comment by Shivangi-ch** [comment]
@abhijeet007rocks8 Resolved

**Pull request merged**
