### PR TITLE
Added a Login page

### PR DESCRIPTION
**Pull request by Shivangi-ch**
Fixes : #257 
Screenshot from 2021-05-17 20-18-58

### CODE REVIEW

**Comment by Shivangi-ch** [comment]
YES

**Comment by Shivangi-ch** [comment]
@abhijeet007rocks8 @DhairyaBahl Please review!

**Review by abhijeet007rocks8 — CHANGES_REQUESTED** [review]
Merge Conflicts Please resolve them.

**Comment by Shivangi-ch** [comment]
@abhijeet007rocks8 Conflicts resolved

**Review by abhijeet007rocks8 — APPROVED** [review]

**Pull request merged**
