### PR TITLE
the dropdown arrow key(scroll to bottom) added to the bottom right corner

### PR DESCRIPTION
**Pull request by Shivangi-ch**
Fixes: #255 
Screenshot from 2021-05-17 02-06-04

### CODE REVIEW

**Comment by Shivangi-ch** [comment]
@abhijeet007rocks8 @DhairyaBahl Please review!

**Comment by Shivangi-ch** [comment]
YES

**Review by abhijeet007rocks8 — CHANGES_REQUESTED** [review]
Please resolve the merge conflict occurring in App.js file

**Comment by Shivangi-ch** [comment]
@abhijeet007rocks8 Conflicts resolved.

**Review by abhijeet007rocks8 — APPROVED** [review]

**Pull request merged**
