### PR TITLE
Theme change is now working for contact us form.

### PR DESCRIPTION
**Pull request by Shivangi-ch**
Fixes issue: #208 
Screenshot from 2021-05-13 02-12-22
Screenshot from 2021-05-13 02-12-30

### CODE REVIEW

**Comment by Shivangi-ch** [comment]
YES

**Comment by Shivangi-ch** [comment]
@abhijeet007rocks8 @DhairyaBahl Please review

**Review by DhairyaBahl — APPROVED** [review]
Everything Looks Great !!

**Comment by Shivangi-ch** [comment]
@DhairyaBahl @abhijeet007rocks8 Please add gssoc level label.

**Comment by Shivangi-ch** [comment]
@abhijeet007rocks8 @DhairyaBahl
# Please add the labels!

**Pull request merged**
