### PR TITLE
added Read-More-Less functionality

### LINKED ISSUE #25: Read More
### Description

Currently this app shows full messages, it doesn't matter how long they are, chat will show full message. How about read more kind of a thing which will be great for the app. 

### Example Picture

readmore

### PR DESCRIPTION
**Pull request by shreyanshi16**
fixes #25

### CODE REVIEW

**Comment by shreyanshi16** [comment]
image
image
image

Read more button will appear to a message having more than 180 characters.

**Review by DhairyaBahl — COMMENTED** [review]
@shreyanshi16 Do add yourself in the contributors.md list. Rest looks perfect to me. thanks for solving the issue.

**Comment by shreyanshi16** [comment]
@DhairyaBahl Welcome for assigning me this issue. I want to request you to add the GSSOC'21 label to this issue as I am solving this issue under GSSOC'21.

**Comment by DhairyaBahl** [comment]
@shreyanshi16 kindly squash all of your commits . Usually I add the gssoc label after the successful merge of the PR but no issues ! I will add them :)

**Comment by shreyanshi16** [comment]
Hey, @DhairyaBahl I am trying very hard to squash all commits to one but I am not being able to do that. Do you know any other way to do this?

**Comment by shreyanshi16** [comment]
@DhairyaBahl I followed the following steps:

git rebase -i HEAD~5
replaced pick with squash

And now when I am trying to commit I am getting this message
image

Please guide how to fix this error.

**Comment by DhairyaBahl** [comment]
@shreyanshi16 what do you see when you run git status ?

**Comment by shreyanshi16** [comment]
image

**Comment by DhairyaBahl** [comment]
@shreyanshi16 Try doing git add --all and then again do the git status

**Comment by shreyanshi16** [comment]
@DhairyaBahl Still getting the same message.

**Comment by DhairyaBahl** [comment]
@shreyanshi16 that's odd. No issues i will squash them myself. don't take headache for that just resolve the conflicting files.

**Comment by DhairyaBahl** [comment]
@shreyanshi16 If you feel any difficulty resolving the conflicts then free feel to ask. Either here or on the discord server .

**Review by DhairyaBahl — APPROVED** [review]
I am approving this PR but do add yourself in the  contributors.md list in another PR. Looking forward to another PR for the same.

**Comment by shreyanshi16** [comment]
@DhairyaBahl Conflict is solved. Thanks a lot for your guidance and support.

**Comment by DhairyaBahl** [comment]
@shreyanshi16 Kindly add yourself in the contributors.md so that I can keep a track of all the contributors. Thank you for the contribution 😄 . Do check out other issues as well.

**Comment by shreyanshi16** [comment]
@DhairyaBahl sure I will make another PR.

**Comment by DhairyaBahl** [comment]
@shreyanshi16 Thanks

**Comment by AnjaliPatle** [comment]
Hey. I just cloned the repo and it seems like this PR changes the code a bit. I'm getting errors because in `src/Messages.js` the div on `line 28` has been repeated and it wasn't closed properly. I think it was just a small mistake and deleting `line 28, 29 and 30` and putting the `<ReadMore>` element inside the pre-existing div on `line 31` should fix it. Please look into it.

image

**Comment by shreyanshi16** [comment]
@AnjaliPatle Thank you for informing me about the error and sorry for the inconvenience caused to you due to me. I have fixed the error and have made a PR for the same. Once PR will merge error will be solved in the main repo.

**Comment by DhairyaBahl** [comment]
@AnjaliPatle Thank You ! Really appreciate your concern for the project

**Pull request merged**
