### PR TITLE
Message sent by pressing enter key

### PR DESCRIPTION
**Pull request by Shivangi-ch**
Fixed issue #162
Message can now be send by pressing enter key.

### CODE REVIEW

**Comment by Shivangi-ch** [comment]
@DhairyaBahl Please Review .

**Review by DhairyaBahl — APPROVED** [review]
@Shivangi-ch Well done ! I am merging this PR ! Do checkout other issues as well .

**Comment by DhairyaBahl** [comment]
Thanks you for the contribution ^_^

**Comment by Shivangi-ch** [comment]
@DhairyaBahl I think you forgot to add the labels for GSSOC, please add the labels which were in the coressponding issue.

**Pull request merged**
