### PR TITLE
Send message when enter key is pressed

### LINKED ISSUE #105: Send message with the enter key
Currently in the app, your message is sent only when you click on the arrow button. We can keep a feature where the message is sent even after pressing the enter key in your keyboard (like other messaging apps) 
I would like to try this out under GSSOC'21 !

### PR DESCRIPTION
**Pull request by AmrutaKoshe**
resolves #105 
Now, whenever a user presses the enter key after writing a message, the message can be delivered.

### CODE REVIEW

**Comment by abhijeet007rocks8** [comment]
Hey @AmrutaKoshe can you attach  a working demo video of the issue being resolved.

**Comment by AmrutaKoshe** [comment]
You can see that the message is delivered on pressing enter! 

ezgif com-gif-maker

**Review by DhairyaBahl — COMMENTED** [review]
@AmrutaKoshe Hello ! Thanks for working on the issue. Sorry for delay from my side. Is this final ? Kindly confirm once. Everything seems perfect to me !

Commits are squashed ! Perfect video demonstration. Well Done. Confirm it once and I will merge it asap. Sorry again for the delay.

**Comment by AmrutaKoshe** [comment]
> @AmrutaKoshe Hello ! Thanks for working on the issue. Sorry for delay from my side. Is this final ? Kindly confirm once. Everything seems perfect to me !
> 
> Commits are squashed ! Perfect video demonstration. Well Done. Confirm it once and I will merge it asap. Sorry again for the delay.

Yes it is final!

**Comment by DhairyaBahl** [comment]
@AmrutaKoshe Thank you for the contribution ^_^

**Pull request merged**
