### PR TITLE
Dark theme issue of login page fixed.

### PR DESCRIPTION
**Pull request by Shivangi-ch**
Fixes : #455

### CODE REVIEW

**Comment by Shivangi-ch** [comment]
@abhijeet007rocks8 Please review.

**Comment by Shivangi-ch** [comment]
YES

**Comment by abhijeet007rocks8** [comment]
Merge conflicts please resolve

**Comment by Shivangi-ch** [comment]
@abhijeet007rocks8 Conflicts resolved.

**Pull request merged**
