### PR TITLE
Changed Input Font-size and padding

### LINKED ISSUE #110: The Type a message section, can be made bigger.
Maybe its Z index can be increased as well for better visuals.

### PR DESCRIPTION
**Pull request by akshay1027**
Changed Input Font-size and padding to make the input box visually appealing. 
fixes #110

### CODE REVIEW

**Review by DhairyaBahl — APPROVED** [review]
Everything seems to be OK !

**Comment by abhijeet007rocks8** [comment]
Is there any functionality added in the '+' button??

**Comment by akshay1027** [comment]
There is no functionality added in the '+' button!

**Comment by DhairyaBahl** [comment]
@dilemmawalker from next time do tell the contributors to squash the commits otherwise it can harm their points. Right now these were counted as two commits but it should be counted as one. Keep this in mind from next time ^_^

**Comment by dilemmawalker** [comment]
Sure @DhairyaBahl , will keep that in mind.

**Pull request merged**
