### PR TITLE
About us page 

### PR DESCRIPTION
**Pull request by akshay1027**
Partial fix of  #132
About us page! Fully responsive, Matching UI, changed Navbar colour as well, added routing!

### CODE REVIEW

**Comment by akshay1027** [comment]
@abhijeet007rocks8 please check this out! Thank you!

**Comment by abhijeet007rocks8** [comment]
Just squash the commits into one rest all looks good

**Review by DhairyaBahl — APPROVED** [review]
Everything seems great to me !! I am merging this PR 🙂

**Comment by DhairyaBahl** [comment]
@akshay1027 Thanks for your contribution ! Do check out other issues as well 🙂

**Pull request merged**
