### PR TITLE
Aboutus page

### PR DESCRIPTION
**Pull request by akshay1027**
have made the About us page. Please let me know if you are okay with this design! it's fully responsive! Tried the match with the logo of this website by adding gradient colours as well, used react-router as well for routing! @abhijeet007rocks8 @DhairyaBahl

### CODE REVIEW

**Comment by akshay1027** [comment]
Let me know if you like the colours, or else we can change them 🙌🏻🚀

**Comment by abhijeet007rocks8** [comment]
@akshay1027  Can you share the scshot when light theme is applied and also in mobile view

**Comment by akshay1027** [comment]
i have not made light mode UI yet, this itself took long time! Here are the Mobile layout egs:

**Comment by akshay1027** [comment]
am thinking maybe we can make the colour a bit lighter..it seemed light in my laptop, but when i see these screenshot in phone, its bright, this is my opinion tough! let me know about this, so that i can add few more content to this about us page!

**Comment by akshay1027** [comment]
any update? please let me know @abhijeet007rocks8 @DhairyaBahl

**Comment by akshay1027** [comment]
i have pulled in all the changes from master, i will maybe open another PR? @abhijeet007rocks8 @DhairyaBahl

**Comment by abhijeet007rocks8** [comment]
Have you opened the other PR??

**Comment by akshay1027** [comment]
Okay, I will open now 🙌🏻

**Comment by abhijeet007rocks8** [comment]
Just a suggestion for the light mode just change the background to white the font colors will be visible then too
.

**Comment by akshay1027** [comment]
The about us page is in different component, so we have to prop drilling as home page is in app.js file only, so no prop drilling is needed there. I don't want to try something and break the UI, I think first we can finish this off and look at that later..this is my opinion.

**Comment by akshay1027** [comment]
Also thinking to make the colours a bit light, it's very flashy at the moment when viewed through phone

**Comment by DhairyaBahl** [comment]
@akshay1027 There is a typo in the header ! Its messenger not messengar ! Make it right ! Rest is being handled perfectly by abhijeet.

@abhijeet007rocks8  Feel free to approve the changes but I will merge these myself . Hope you understand 🙂 Thanks

**Pull request closed without merging**
