### PR TITLE
Mobile UI, send feature, logo, responsive input box

### LINKED ISSUE #125: No send feature in mobile version and improvements in mobile version
No, send feature in mobile or responsive version.

2021-03-28 (5)_LI

### PR DESCRIPTION
**Pull request by akshay1027**
Have made the mobile UI, with send feature, fully responsive layout with a responsive input box, made logo responsive as well!
@DhairyaBahl please check these out! Also, please add labels if you like the changes and want to merge them! Thank you!

fixes #125

### CODE REVIEW

**Comment by abhijeet007rocks8** [comment]
Can you provide a padding beside the message bar.

**Comment by akshay1027** [comment]
Can you please tell me where you exactly want the padding ? Please tell with screen shot of possible @abhijeet007rocks8

**Review by abhijeet007rocks8 — CHANGES_REQUESTED** [review]
Provide a little margin between both sides of message bar.

**Comment by akshay1027** [comment]
Okay, understood 🙌🏻

**Comment by abhijeet007rocks8** [comment]
> Can you please tell me where you exactly want the padding ? Please tell with screen shot of possible @abhijeet007ro
Currently the message bar is stuck to the left side and right side of screen give a little space between edge and input bar.

**Comment by akshay1027** [comment]
are you okay with this @abhijeet007rocks8 
let me know if you will need further changes

**Comment by abhijeet007rocks8** [comment]
Try clicking on the mobile option in the developer window and send some scshots

**Comment by abhijeet007rocks8** [comment]
horizontal margin approx 0.3rem - 0.5rem

**Comment by akshay1027** [comment]
Rest of the code is in px, so keeping in px would be better I feel

**Comment by abhijeet007rocks8** [comment]
> Rest of the code is in px, so keeping in px would be better I feel

5px then

**Comment by akshay1027** [comment]
i have done 1px, 5px will make the box unresponsive, making 1px solves the white line that comes in the right side of the box, i think that is what you wanted to solve!

**Comment by abhijeet007rocks8** [comment]
> i have done 1px, and increased padding! there is a little gap now!

cool push the code

**Review by abhijeet007rocks8 — APPROVED** [review]

**Comment by akshay1027** [comment]
Please add labels as well @abhijeet007rocks8, here is the issue #125

**Pull request merged**
