### PR TITLE
Issue 48 Favicon not showing

### LINKED ISSUE #48: Change default site title and favicon
Hey @DhairyaBahl !
I just noticed that we are still using the default the site title and favicon provided with the React boilerplate code.
I think we should change it to something matching our site's objective. [GSSOC`21 participant]
Screenshot 2021-03-10 at 11 16 22 PM

### PR DESCRIPTION
**Pull request by dig9074vijay**
I think favicon should be visible now, please check. fixes #48 
I have checked it on the following devices and browers:
On safari:
Screenshot 2021-03-11 at 2 11 36 PM
on Chrome:
Screenshot 2021-03-11 at 2 11 26 PM
on iPhone 11:
Screenshot 2021-03-11 at 2 12 27 PM
on Android:
WhatsApp Image 2021-03-11 at 14 31 46

### CODE REVIEW

**Comment by dig9074vijay** [comment]
Hey @DhairyaBahl ! Please review it.

**Comment by DhairyaBahl** [comment]
@dig9074vijay FIles are conflicting ! and what this PR is about ?? Is it about the messenger favicon ? then it is already fixed !

**Comment by dig9074vijay** [comment]
> @dig9074vijay FIles are conflicting ! and what this PR is about ?? Is it about the messenger favicon ? then it is already fixed !

Yes it was for favicon, since it's fixed already I can close this PR or I can fix the merge conflicts and then you can merge it. What do you want me to do?

**Comment by dig9074vijay** [comment]
@DhairyaBahl I have fixed the conflicts

**Comment by DhairyaBahl** [comment]
@dig9074vijay I am afraid to say that there is no need to merge the changes that are already there. As per the guidelines of GSSOC, strict action will be taken on spammy pull requests. So, I won't be merging this PR. Sorry for inconvenience caused. Do check out other issues.

Thanks and Regards ! Really Appreciate the effort.

**Comment by dig9074vijay** [comment]
@DhairyaBahl Thanks for pointing that out.

**Pull request closed without merging**
