### PR TITLE
Contact us form modified.

### PR DESCRIPTION
**Pull request by Shivangi-ch**
Fixes issue: #188 
I have made the contact us form more attractive and user-friendly.
Screenshot from 2021-05-09 22-16-09

### CODE REVIEW

**Comment by Shivangi-ch** [comment]
YES

**Review by abhijeet007rocks8 — CHANGES_REQUESTED** [review]
Please Reduce button size and align it in middle horizontally

**Comment by Shivangi-ch** [comment]
@abhijeet007rocks8 I have made the requested changes .Kindly review

**Review by abhijeet007rocks8 — APPROVED** [review]
@Shivangi-ch Great Work

**Pull request merged**
