### PR TITLE
Fixed logo distortion in Safari

### LINKED ISSUE #51: Messenger logo is distorted in Safari
### **In Safari:**
Screenshot 2021-03-11 at 12 27 33 PM

### **In Chrome:**

Screenshot 2021-03-11 at 12 29 58 PM

@DhairyaBahl I would like to fix it as a gssoc`21 participant. 😁

### PR DESCRIPTION
**Pull request by dig9074vijay**
Fixed #51 
After fixing the distortion:
Screenshot 2021-03-11 at 3 14 12 PM

### CODE REVIEW

**Comment by dig9074vijay** [comment]
@DhairyaBahl Please review it!

**Review by DhairyaBahl — APPROVED** [review]

**Comment by DhairyaBahl** [comment]
@dig9074vijay Thanks for the contribution. Do make another PR and add yourself in the contributors.md list if you haven't done that till now !

**Comment by dig9074vijay** [comment]
Thanks @DhairyaBahl for giving me the opportunity to contribute to this project.😁

**Comment by dig9074vijay** [comment]
@DhairyaBahl Please add the labels for the contribution to be counted in GSSoC.

**Comment by DhairyaBahl** [comment]
@dig9074vijay Okay checking it out ! and will add appropriate labels to the PR if they are missing

**Comment by dig9074vijay** [comment]
> @dig9074vijay Okay checking it out ! and will add appropriate labels to the PR if they are missing

@DhairyaBahl Much appreciated!

**Comment by dig9074vijay** [comment]
@DhairyaBahl I think you added the labels to another PR of mine. Please add the labels to this one, sooner the better✌🏻

**Comment by DhairyaBahl** [comment]
@dig9074vijay Added the labels

**Comment by dig9074vijay** [comment]
@DhairyaBahl Thanks!

**Pull request merged**
