### PR TITLE
Added Scroll to bottom button

### LINKED ISSUE #212: Add a "Scroll to Bottom" button on Home Page
## Problem:

Since a user is most likely concerned with the latest messages only, if he/she wants to read messages and not send any, a lot of scrolling will be needed which is bad UX

## Solution:

A button that scrolls to the bottom will make UX much better

## Screenshot
image

### PR DESCRIPTION
**Pull request by N-Shar-ma**
Fixes #212

### CODE REVIEW

**Comment by N-Shar-ma** [comment]
YES

**Comment by abhijeet007rocks8** [comment]
Can you share the gif of your issue fix

**Comment by DhairyaBahl** [comment]
@N-Shar-ma Kindly send some picture or gif of the working of the feature and I will merge it right away !

**Review by abhijeet007rocks8 — APPROVED** [review]

**Comment by N-Shar-ma** [comment]
Here's the gif:


Thank you for merging!

**Pull request merged**
