### PR TITLE
Enhanced the design for fixed header

### PR DESCRIPTION
**Pull request by yokesh004**
I have worked on the App.css file to make the change the alignment/order of the elements present in the header.  Now the header looks like the below image
image

Hope you like this design.  Thank you.

### CODE REVIEW

**Review by DhairyaBahl — CHANGES_REQUESTED** [review]
design looks great to me but can you also show me the phone view of the app ?

**Comment by yokesh004** [comment]
> design looks great to me but can you also show me the phone view of the app ?

image

**Comment by DhairyaBahl** [comment]
@yokesh004 Why is that white line coming in the right and also that blue header is not covering the whole screen horizontally ? or is it just the issue of picture ? Kindly confirm and resend the image if this is a picture issue.

**Comment by yokesh004** [comment]
This is the original image
image

**Review by DhairyaBahl — APPROVED** [review]

**Comment by DhairyaBahl** [comment]
@yokesh004 Merged ! Thank You 😄

**Comment by yokesh004** [comment]
> @yokesh004 Merged ! Thank You

Thank you @DhairyaBahl

**Pull request merged**
