### PR TITLE
Fixed the code by adding some deleted component

### PR DESCRIPTION
**Pull request by garvitgupta13**
Fixes: #103 

Someone removed the `FormControl`, `but` and `SendIcon` from the repo, so I added them in a proper way.
image

### CODE REVIEW

**Comment by garvitgupta13** [comment]
Hey @DhairyaBahl please have a look on this.
Please add the necessary gssoc21 labels.

**Comment by garvitgupta13** [comment]
These are major changes that I did
image

**Review by DhairyaBahl — APPROVED** [review]
Everything now seems to be perfect to me ! I am merging this PR.

**Comment by DhairyaBahl** [comment]
@garvitgupta13 Thank for the contribution. Do check out other issues as well !

**Pull request merged**
