### PR TITLE
Footer text issue fixed.

### PR DESCRIPTION
**Pull request by Shivangi-ch**
Fixes: #325 
Screenshot from 2021-05-24 02-34-41

### CODE REVIEW

**Comment by Shivangi-ch** [comment]
YES

**Comment by Shivangi-ch** [comment]
@abhijeet007rocks8 Please review

**Comment by abhijeet007rocks8** [comment]
@Shivangi-ch Merge Conflict

**Comment by Shivangi-ch** [comment]
@abhijeet007rocks8 Conflict resolved.

**Review by abhijeet007rocks8 — APPROVED** [review]

**Comment by Shivangi-ch** [comment]
@abhijeet007rocks8 Please add the level labels.

**Pull request merged**
