### PR TITLE
added favicon and changed head-title

### PR DESCRIPTION
**Pull request by Himanshu16Singh**
image

### Can you please merge it ?

### CODE REVIEW

**Review by DhairyaBahl — CHANGES_REQUESTED** [review]
Do add urself in the contributors.md list

**Comment by DhairyaBahl** [comment]
@Himanshu16Singh And then also squash the commits so that I can merge them. Cheers 😄

**Review by DhairyaBahl — CHANGES_REQUESTED** [review]
Kindly squash all the commits

**Comment by Himanshu16Singh** [comment]
How can I squash my commits ?

**Comment by DhairyaBahl** [comment]
@Himanshu16Singh 

https://levelup.gitconnected.com/how-to-squash-git-commits-9a095c1bc1fc

**Comment by Himanshu16Singh** [comment]
Can you please check the squashed files commit ? Is it okay ?
As I finding difficulty in squashing commits.

**Comment by Himanshu16Singh** [comment]
Please reply ASAP.

**Comment by DhairyaBahl** [comment]
@Himanshu16Singh You can remake the PR and I don't have any problem with that. But this time if you are stuck somewhere do ping me and stop at that point so that we can solve that issue together. 

All the best 👍

**Comment by Himanshu16Singh** [comment]
Okay, next time I will ping you.

**Pull request closed without merging**
