### PR TITLE
Code cleaned.

### PR DESCRIPTION
**Pull request by Shivangi-ch**
Fixes: #220

### CODE REVIEW

**Comment by Shivangi-ch** [comment]
YES

**Comment by Shivangi-ch** [comment]
@abhijeet007rocks8 @DhairyaBahl Please review!

**Review by abhijeet007rocks8 — CHANGES_REQUESTED** [review]
PLease resolve the merge conflicts

**Comment by Shivangi-ch** [comment]
@abhijeet007rocks8 Conflicts resolved

**Review by abhijeet007rocks8 — APPROVED** [review]

**Pull request merged**
