### PR TITLE
Better UI colors

### PR DESCRIPTION
**Pull request by SanskritiKushik5**

### CODE REVIEW

**Comment by abhijeet007rocks8** [comment]
@SanskritiKushik5 can you please share the scshots of before the changes and after the changes for better understanding

**Comment by SanskritiKushik5** [comment]
Sure!
Before:
before-light-mode
before-dark-mode

After:
light-mode
dark-mode

**Comment by DhairyaBahl** [comment]
@SanskritiKushik5 Thank you for contribution

**Comment by DhairyaBahl** [comment]
@SanskritiKushik5 Do check out some other issues also 😄

**Pull request merged**
