### PR TITLE
Footer Enhancement

### PR DESCRIPTION
**Pull request by Sristi27**
Yes that works perfectly fine!
Created the PR for issue137.Do check this! @DhairyaBahl

### CODE REVIEW

**Review by DhairyaBahl — COMMENTED** [review]
@Sristi27 It would be great if you can change the name of the PR into something meaningful like " Enhancing footer and improving layout " . and then you should also squash all your commits.

Thanks ^_^

**Comment by DhairyaBahl** [comment]
@Sristi27 Able to squash the commits ? If you find any difficulties doing the same then ping me right away and I will do it myself. All new contributors find it difficult to squash the commits but no worries.

**Comment by Sristi27** [comment]
> @Sristi27 Able to squash the commits ? If you find any difficulties doing the same then ping me right away and I will do it myself. All new contributors find it difficult to squash the commits but no worries. 

No actually I am not able to do it!

**Comment by DhairyaBahl** [comment]
@Sristi27 No issues ! I will do that for you ^_^ I am merging this PR now !

**Comment by DhairyaBahl** [comment]
@Sristi27 Thank you for the contribution ^_^ Do check out other issues as well.

**Comment by Sristi27** [comment]
> @Sristi27 Thank you for the contribution ^_^ Do check out other issues as well.

Sure! 
Thank you for the opportunity!

**Pull request merged**
