### PR TITLE
improving the text message bar - Issue #33

### PR DESCRIPTION
**Pull request by Arshanshagarwal**
I have resolved the merge conflicts as well

Before: 
Capture

The previous input bar looked very out of place. I improved the looks by introducing a similar and pleasing background to the input bar. I also attached the theme colors according to the mode (dark or light)

After: 
Capture1

### CODE REVIEW

**Comment by abhijeet007rocks8** [comment]
Great, but can you send the scshot of mobile view and make the send button separate from text area. as attachments  will also come there.

**Comment by abhijeet007rocks8** [comment]
Great, but can you send the scshot of mobile view and make the send button separate from text area. as attachments  will also come there.

**Comment by abhijeet007rocks8** [comment]
Great, but can you send the scshot of mobile view and make the send button separate from text area. as attachments  will also come there.

**Comment by DhairyaBahl** [comment]
@Arshanshagarwal Kindly recheck the app !

**Pull request closed without merging**
