### PR TITLE
Added Contributor

### LINKED ISSUE #69: Adding Contributor section in readme  ( Automatically )
I will like to add a feature this will update contributor list in read me automatically !! Will start to work on this issue as soon as i get assigend !!

### PR DESCRIPTION
**Pull request by rohank2502**
Fixes #69

### CODE REVIEW

**Review by DhairyaBahl — CHANGES_REQUESTED** [review]
Do add yourself in the contributors.md list

**Comment by rohank2502** [comment]
> 
> 
> Do add yourself in the contributors.md list

Dont worry  it is automated will get added after this pull request gets merged :)

**Comment by DhairyaBahl** [comment]
@rohank2502 I am talking about the contributors.md file in which you have to add yourself manually !

**Comment by rohank2502** [comment]
> 
> 
> @rohank2502 I am talking about the contributors.md file in which you have to add yourself manually !

Oo Sorry I will So it now just a min !!

**Comment by rohank2502** [comment]
Done !!

**Comment by DhairyaBahl** [comment]
@rohank2502 Merged ! Thank you for the contribution 🔥

**Comment by rohank2502** [comment]
My pleasure

**Pull request merged**
