### PR TITLE
added authentication system and chat group system

### PR DESCRIPTION
**Pull request by robinsingh-ai**
Solves conflicting files issues in #107 PR
Solves #31 
Screenshots
React Messenger App SS 1

React Messenger App SS 2

React Messenger APP ss 3

### CODE REVIEW

**Comment by abhijeet007rocks8** [comment]
@robin025 looks good to me can you just replace the time shown in the messages to how its being shown in the current version.

@DhairyaBahl Review it once. I did but you should do to and then merge it.

**Review by DhairyaBahl — CHANGES_REQUESTED** [review]
@robin025  You did a great Job !! Superb ! Just fix the time to how it is being shown right now ! Rest seems perfect to me. Really appreciate the effort  ^_^

**Comment by robin025** [comment]
> @robin025  You did a great Job !! Superb ! Just fix the time to how it is being shown right now ! Rest seems perfect to me. Really appreciate the effort  ^_^

Actually @DhairyaBahl  and @abhijeet007rocks8  the time which we are showing is the server time stamp
For example if someone msgs from uk so their local time will be completely different from us...so that's why I used this server timestamp which Google Firebase uses.

**Comment by abhijeet007rocks8** [comment]
> > @robin025  You did a great Job !! Superb ! Just fix the time to how it is being shown right now ! Rest seems perfect to me. Really appreciate the effort  ^_^
> 
> Actually @DhairyaBahl and @abhijeet007rocks8 the time which we are showing is the server time stamp
> For example if someone msgs from uk so their local time will be completely different from us...so that's why I used this server timestamp which Google Firebase uses.

You can get the device timezone and make the time difference accordingly

**Comment by robinsingh-ai** [comment]
Hello @DhairyaBahl  ,
I had a discussion with Praveen who is doing all the leaderboard stuff of GSSoC21 and he told all of us that the GSSoC21 tag should look like *GSSoC21* and it's case sensitive, so if the tag doesn't look like this *GSSoC21* then that PR will not be counted, so can you please update the tag in all my PRs thatbhave reference to issue #123 


Thankyou

**Comment by abhijeet-chatterjee** [comment]
> Hello @DhairyaBahl ,
> I had a discussion with Praveen who is doing all the leaderboard stuff of GSSoC21 and he told all of us that the GSSoC21 tag should look like _GSSoC21_ and it's case sensitive, so if the tag doesn't look like this _GSSoC21_ then that PR will not be counted, so can you please update the tag in all my PRs that have reference to issue #123
> 
> Thankyou
 
During Previous stages also this label was used and the merges of other were considered and points were appointed. Can you reconfirm with him??

**Comment by robinsingh-ai** [comment]
> > Hello @DhairyaBahl ,
> > I had a discussion with Praveen who is doing all the leaderboard stuff of GSSoC21 and he told all of us that the GSSoC21 tag should look like _GSSoC21_ and it's case sensitive, so if the tag doesn't look like this _GSSoC21_ then that PR will not be counted, so can you please update the tag in all my PRs that have reference to issue #123
> > Thankyou
> 
> During Previous stages also this label was used and the merges of other were considered and points were appointed. Can you reconfirm with him??

Hello @abhijeet007rocks8 
Really sorry for inconvenience, actually I was initially perplexed by the GSSoC21 label tag issue, but eventually realised that these labels are case insensitive, so no need to change this
Again sorry for the inconvenience

Thank you

**Comment by abhijeet-chatterjee** [comment]
> > > Hello @DhairyaBahl ,
> > > I had a discussion with Praveen who is doing all the leaderboard stuff of GSSoC21 and he told all of us that the GSSoC21 tag should look like _GSSoC21_ and it's case sensitive, so if the tag doesn't look like this _GSSoC21_ then that PR will not be counted, so can you please update the tag in all my PRs that have reference to issue #123
> > > Thankyou
> > 
> > 
> > During Previous stages also this label was used and the merges of other were considered and points were appointed. Can you reconfirm with him??
> 
> Hello @abhijeet007rocks8
> Really sorry for inconvenience, actually I was initially perplexed by the GSSoC21 label tag issue, but eventually realised that these labels are case insensitive, so no need to change this
> Again sorry for the inconvenience
> 
> Thank you

Fixed It.

**Pull request merged**
