### PR TITLE
#11 Issue: Dark Mode White Layer Add: Top and Bottom

### PR DESCRIPTION
**Pull request by vieee**
Final Look
(PC view)
Screenshot_2021-03-07 React App

(Mobile View)
Screenshot_2021-03-07 React App(1)

### CODE REVIEW

**Review by DhairyaBahl — CHANGES_REQUESTED** [review]
I think we should make the border thinner. Do try for 1px or 0.5 px .

Reason : the main purpose of border is to differentiate between the footer, messages and the header which can be done by thinner border .

**Comment by vieee** [comment]
Hi @DhairyaBahl, updated it to 1px,..
It looks like this..

Screenshot_2021-03-07 React App(2)

**Review by DhairyaBahl — CHANGES_REQUESTED** [review]
Add yourself in the contributors.md list and squash of your commits

**Review by DhairyaBahl — COMMENTED** [review]
Kindly squash all of your commits so that i will merge this ! 

Thanks :)

**Comment by vieee** [comment]
> Kindly squash all of your commits so that i will merge this !
> 
> Thanks :)

I didn't get you

**Comment by DhairyaBahl** [comment]
@vieee If you are having difficulties in  squashing the commits then I can assist you ! 👍

**Comment by vieee** [comment]
Yes @DhairyaBahl, when tried to squash all commits to one, I followed 

```
git reset --soft HEAD~5
git commit -m "New message for the combined commit"
git push origin +master
```

But, instead of squashing, it just added one more commit. Not sure how to squash all commits.

**Comment by vieee** [comment]
I've pushed the css file and updated the Contributors.md file, should any other thing be done ?

**Comment by DhairyaBahl** [comment]
@vieee Your PR is conflicting with the codebase. Kindly resolve all the conflicts , squash your commits. Because currently I can't merge it.

**Comment by vieee** [comment]
Hi @DhairyaBahl, created a PR request with an updated version, as per current repository condition..

PR request: #79

**Comment by vieee** [comment]
Sorry for the inconvenience..

**Pull request closed without merging**
