### PR TITLE
added messages into component based architecture

### LINKED ISSUE #113: Change frontend Architecture to a component-based one!
Change frontend Architecture to a component-based one instead of everything in a single file! In this way, it would easier to find bugs and divide components to individual contributors!

### PR DESCRIPTION
**Pull request by akshay1027**
please check these out @DhairyaBahl . Fixes #113

### CODE REVIEW

**Comment by DhairyaBahl** [comment]
@akshay1027 Kindly add the screenshots depicting the changes you made .

**Comment by akshay1027** [comment]
Introduced component-based architecture, Changed file locations in app.js, etc, removed un-used lines of code messages file.



@DhairyaBahl

**Comment by abhijeet007rocks8** [comment]
@akshay1027 Can you also add the scshot of the working app??

**Comment by akshay1027** [comment]
Screenshot of working app

**Review by DhairyaBahl — APPROVED** [review]
Everything seems okay to me ! but I won't be able to check it thoroughly due to time constraints !  

@abhijeet007rocks8  Kindly make sure that he is not breaking any of the existing features and don't worry about the rest. If some minor issue do comes up later, then we can always make an issue for the same for new contributors.

**Pull request merged**
