### PR TITLE
update contributing.md

### PR DESCRIPTION
**Pull request by khareyash05**
With reference to issue #84 
Added the following 
1.Difference between GIT and GITHUB
2.How to clone,fork repository
3.How to create a branch and then use git push to push to repo
4.Create a PR
5.Squash commits in a single issue into one
6, Updating the forked and local repo as the updations are made in the upstream

### CODE REVIEW

**Review by DhairyaBahl — APPROVED** [review]
Everything seems to be perfect 😄 Well Done !

**Comment by DhairyaBahl** [comment]
Thank You for the contribution ! Do check out other issues as well.

**Comment by khareyash05** [comment]
@DhairyaBahl Thank you !

**Comment by khareyash05** [comment]
@DhairyaBahl  Could you pls add a level label and a GSSOC label to the PR as well because adding a level label to the PR is only being counted
Thanx!

**Comment by DhairyaBahl** [comment]
@khareyash05 Added ! Sorry I forgot to add them ^_^

**Comment by khareyash05** [comment]
@DhairyaBahl no problems thanx

**Pull request merged**
