### PR TITLE
Inputbox made responsive

### PR DESCRIPTION
**Pull request by akshay1027**
The input box is made fully responsive!
Fixes: #159 

screenshots:

### CODE REVIEW

**Comment by akshay1027** [comment]
chech these out @abhijeet007rocks8 @DhairyaBahl

**Comment by abhijeet007rocks8** [comment]
@akshay1027  Can you change the background color of input area it should appear different from rest of the layout
Rest is great. Nice work

**Review by abhijeet007rocks8 — CHANGES_REQUESTED** [review]
change the background color of input area

**Comment by akshay1027** [comment]
Shall i do that in another PR, first we will nail this down @abhijeet007rocks8

**Review by abhijeet007rocks8 — APPROVED** [review]

**Pull request merged**
