### PR TITLE
Hiding api keys

### PR DESCRIPTION
**Pull request by garvitgupta13**
Fix issue : #229 

I have added all the API keys in `.env` file and included that in `.gitignore` file

### CODE REVIEW

**Comment by garvitgupta13** [comment]
YES

**Comment by garvitgupta13** [comment]
Hey @DhairyaBahl I think we should remove `.env` file from `gitignore` file, otherwise, people running them in local system would not be able to use it on their local machine

Please let me know your views on it.

**Comment by abhijeet007rocks8** [comment]
> Hey @DhairyaBahl I think we should remove `.env` file from `gitignore` file, otherwise, people running them in local system would not be able to use it on their local machine
> 
> Please let me know your views on it.

Exactly what i was thinking @DhairyaBahl your suggestions.

**Comment by garvitgupta13** [comment]
I guess for now moving the apiKey to `.env` file will be correct and lets make it public

Hey @DhairyaBahl  @abhijeet007rocks8 please let me know your views on it.

**Review by abhijeet007rocks8 — APPROVED** [review]

**Pull request merged**
