### PR TITLE
Multicolor themes added

### PR DESCRIPTION
**Pull request by AakankshaKamal**
Screenshot 2021-04-04 150944
Screenshot 2021-04-04 151029
Screenshot 2021-04-04 151057
Screenshot 2021-04-04 151135
Screenshot 2021-04-04 151200

Here on clicking the button on the right-side user will be displayed the available colorful themes to set the colorful background of the messaging window. It is made responsive too.Changes are made in App.Js ,App.css file and switcher .css is added.

### CODE REVIEW

**Review by DhairyaBahl — CHANGES_REQUESTED** [review]
You seem to be working on a very old version of the project. Kindly resolve all the conflicting files. Also the blue color of the header that you sent me in the screenshots was changed to indigo long ago.

After all this you will have to squash all the commits. But that comes later. First just resolve the conflicting files then I will tell you what to do next.

**Comment by DhairyaBahl** [comment]
@AakankshaKamal Also just to mention, you don't put the branch name like you did in this issue. It is usually something related to the issue. Like "multicolorThemes" . These are some protocols that should be followed when you are contributing to the big organisation.

No need to change that now ^_^ just keep this in mind next time. All the best.

**Comment by AakankshaKamal** [comment]
ok I ll look upon it.

**Comment by AakankshaKamal** [comment]
Resolved the conflicting files

**Comment by DhairyaBahl** [comment]
@AakankshaKamal Send the latest screenshots. Also the icon for dark mode looks pretty weird kindly make it look like a circle. Then you have to squash all your commits.

**Comment by AakankshaKamal** [comment]
ok i ll do it .Can I make a fresh pr with the updated changes with pull request through a new branch?

**Comment by DhairyaBahl** [comment]
@AakankshaKamal What is the problem you are facing in this PR ? We don't create new PRs like this because the conversation is lost in the process. So, feel free to reach out to me if you are facing any problem while squashing the commits. All the new contributors face the same problem in the beginning with squashing. 

All the best ^_^

**Comment by AakankshaKamal** [comment]
Actually I am getting confused when I am running git rebase -i HEAD~3 command, it is showing a number of commits  of other branches too  that is due to the pull command I guess so so should I squash them all and pick my recent commit? Thanks.

**Comment by DhairyaBahl** [comment]
@AakankshaKamal No issues ! Don't take more headache for the same ! You tried well. I will squash the commits for you ^_^ . No issues. Just send me the final screenshots and gif of the app before merging. 

Thanks ^_^

**Comment by AakankshaKamal** [comment]
Screenshot 2021-04-09 080646
Screenshot 2021-04-09 080621
Screenshot 2021-04-09 080556
Screenshot 2021-04-09 080524

Messenger-Profile-1-Microsoft-Ed
Thanks for the help .

**Comment by DhairyaBahl** [comment]
@AakankshaKamal The backgrounds which we are using currently , are they still there ? Can we still apply them ? Or we can only use the new ones ??

**Comment by AakankshaKamal** [comment]
The original section  with the white box will load the previous white background and the user can then switch among it.

**Comment by DhairyaBahl** [comment]
@AakankshaKamal Okkiee then GR8 work !! I am squashing and merging all the commits. 🙂

**Comment by DhairyaBahl** [comment]
@AakankshaKamal Thank you for your contribution 🙂 Do checkout other issues as well or feel free to create new issues.

**Pull request merged**
