### PR TITLE
added favicon and App title

### PR DESCRIPTION
**Pull request by Himanshu16Singh**
made a new PR.
Hope this is fine now.

### CODE REVIEW

**Review by DhairyaBahl — APPROVED** [review]
This PR looks perfect to me.

**Comment by Himanshu16Singh** [comment]
So, Can you please merge it ?

**Comment by DhairyaBahl** [comment]
@Himanshu16Singh you are here for GSSOC right ? So I am finding the exact label that I have to use as a project maintainer. So that it will be counted as a proper contribution.

**Comment by Himanshu16Singh** [comment]
Oh Okay. Yes, I am here for GSSOC'21 .

**Comment by DhairyaBahl** [comment]
@Himanshu16Singh Thank You for the contribution.

**Pull request merged**
