### PR TITLE
Added responsive width of message box.

### PR DESCRIPTION
**Pull request by sagrawal9689**
related to #20 
Screenshot from 2021-02-11 15-22-39
Screenshot from 2021-02-11 15-05-30

### CODE REVIEW

**Review by DhairyaBahl — COMMENTED** [review]
@sagrawal9689 Don't you think that small messages are becoming way too small. So I think we should increase minimum size of the box. What do you say ? :thinking:

**Comment by sagrawal9689** [comment]
Yes @DhairyaBahl , So should I add a min-width of 200 px o the box.

**Comment by DhairyaBahl** [comment]
@sagrawal9689 Yes !! I think go ahead and make those changes. Do upload screenshot of your changes. :smile:

**Comment by sagrawal9689** [comment]
Screenshot from 2021-02-11 15-49-22
Screenshot from 2021-02-11 15-47-11

after adding min-widht 200px

**Review by DhairyaBahl — CHANGES_REQUESTED** [review]
@sagrawal9689 Add yourself in the contributor.md

**Comment by sagrawal9689** [comment]
@DhairyaBahl added

**Review by DhairyaBahl — APPROVED** [review]
Everything seems to be perfect :smile:

**Comment by DhairyaBahl** [comment]
@sagrawal9689 Thanks for your contribution :heart:

**Pull request merged**
