### PR TITLE
Signup responsive

### PR DESCRIPTION
**Pull request by garvitgupta13**
fixed issue #432 
image
image

### CODE REVIEW

**Comment by garvitgupta13** [comment]
YES

**Review by Saatvik21 — CHANGES_REQUESTED** [review]
@garvitgupta13 Can you also increase the font-size of the text as it's very small

**Comment by abhijeet007rocks8** [comment]
Merge conflicts please resolve

**Comment by garvitgupta13** [comment]
> Merge conflicts please resolve

resolved

**Pull request merged**
