### PR TITLE
Message UI

### LINKED ISSUE #141: Card/Messages design can be changed
Card/Messages design can be changed
1) colour
2) box-shadow effect

@abhijeet007rocks8 @DhairyaBahl

### PR DESCRIPTION
**Pull request by akshay1027**
Fixes #141 
The UI of messages is changed! Tried to make them clean so that its professional but also followed the 2 colour pattern and different colour pattern for sender and receiver.

screenshot  
  

:

### CODE REVIEW

**Comment by akshay1027** [comment]
@DhairyaBahl @abhijeet007rocks8 let me know about the changes!

**Comment by abhijeet007rocks8** [comment]
The time text is not visible in this UI also with dark background we should use bright colors and vice versa. So reconsider the color schemes
also please highlight the changes that you made from previous UI

**Comment by akshay1027** [comment]
I have changed the background colours in both sender and receiver side and also the hover effects colour! shall we keep this for light mode, I will change the time stamp colour as well. For dark mode I will try different colours but right now no dark mode colour is there, so have to do that from scratch in another PR @abhijeet007rocks8

**Comment by akshay1027** [comment]
also suggest the colours you want to add because my idea need not be same as yours! hence why if you can suggest the exact colours, it would be way more easier! @abhijeet007rocks8 @DhairyaBahl

**Comment by abhijeet007rocks8** [comment]
@akshay1027 I cannot suggest an exact color but try something bright color for dark background like sky-blue or green
don't know how it will look but you can send schots on discord of various combinations that appeal your eye.

**Pull request closed without merging**
