### PR TITLE
auto-label action  added

### PR DESCRIPTION
**Pull request by Ankita297**
when the contributor makes  a PR gssoc21 label is added .
fix#116 resolve#116
Gurujii com - Google Chrome 22-04-2021 20_23_42

### CODE REVIEW

**Comment by Ankita297** [comment]
@DhairyaBahl  Please  review my PR .

**Comment by DhairyaBahl** [comment]
@Ankita297 Will this be done in every PR ?? There should be something like if someone uses the word gssoc , then only this action should be triggered ! What are your thoughts on this ? Do share ^_^

**Comment by Ankita297** [comment]
@DhairyaBahl it will label to all PR .

**Comment by DhairyaBahl** [comment]
@Ankita297 So try to implement something like it only activates when someone uses the word gssoc ! Getting my point ? All the best !

**Comment by Ankita297** [comment]
Gurujii com - Google Chrome 27-04-2021 22_35_06

**Comment by Ankita297** [comment]
@DhairyaBahl  can this be used ?

**Comment by Ankita297** [comment]
@DhairyaBahl Please  see now .
done by Ankita297 · Pull Request #19 · Ankita297_Story - Google Chrome 04-05-2021 11_56_08 (1)

**Comment by Ankita297** [comment]
@DhairyaBahl Please see now .

**Review by DhairyaBahl — APPROVED** [review]
Everything seems good to me now !! Thanks for the effor ! ^_^ Do checkout other issues as well

**Comment by DhairyaBahl** [comment]
Thanks for the contribution ^_^

**Comment by Ankita297** [comment]
@DhairyaBahl Sir Please add the gssoc  and level label

**Comment by Ankita297** [comment]
@DhairyaBahl Sir Please add the gssoc and level label

**Comment by Ankita297** [comment]
@abhijeet007rocks8 @DhairyaBahl Sir Please add the gssoc and level labels

**Pull request merged**
