### PR TITLE
Faq component | dropdown effect

### PR DESCRIPTION
**Pull request by akshay1027**
faq component added with dropdown effect. If approved,  i have also made an array of objects files where the faq questions are included. I will map over it and display data as we don't want to repeat jsx elements unwantedly!

### CODE REVIEW

**Comment by akshay1027** [comment]
let me know @abhijeet007rocks8 @DhairyaBahl

**Comment by akshay1027** [comment]
IMG_20210512_181643

**Comment by abhijeet007rocks8** [comment]
> let me know @abhijeet007rocks8 @DhairyaBahl , also my lap has not been working for some days. now I am not able to open files, hence why I will sending pics from phone, I hope you guys don't mind it !

no issue images are getting an idea of the fix
and there are merge issues

**Comment by akshay1027** [comment]
thanks! merge issues fixed @abhijeet007rocks8 @DhairyaBahl

**Comment by akshay1027** [comment]
everything is fixed!

**Comment by abhijeet007rocks8** [comment]
its still occurring can you try again

**Comment by akshay1027** [comment]
Can you check it out @abhijeet007rocks8 , I don't knoe why it's happening again, all I did is imported faq component and added that in about page

**Comment by abhijeet007rocks8** [comment]
> Can you check it out @abhijeet007rocks8 , I don't know why it's happening again, all I did is imported faq component and added that in about page

The issue is being generated in app.js file.
So pull the recent changes from the main repo to your fork and then add your changes to it and commit.

**Comment by akshay1027** [comment]
please check now, there are no conflicts!

**Review by abhijeet007rocks8 — APPROVED** [review]
Great Work @akshay1027

**Comment by abhijeet007rocks8** [comment]
Can you mention the issue number ?? for adding label

**Comment by akshay1027** [comment]
this is part of about us page,  #132  @abhijeet007rocks8 , please add labels

**Pull request merged**
