### PR TITLE
Fixed Footer Component, Enhanced Text Input Field and Added two neces…

### PR DESCRIPTION
**Pull request by ankita-04**
…sary buttons(Dark/Light Mode) #59

### CODE REVIEW

**Comment by ankita-04** [comment]
Hey @DhairyaBahl, I have fixed the footer component. It's working perfectly fine. Kindly review and merge it.

**Review by DhairyaBahl — COMMENTED** [review]
@ankita-04 Your PR is conflicting with the codebase. Kindly resolve all the conflicts and do add Screenshots for your changes.

All the best 🔥

**Comment by AdityaTeltia** [comment]
@DhairyaBahl Can you please look at it now

**Comment by DhairyaBahl** [comment]
@ankita-04 
@AdityaTeltia I am still waiting for screenshots from her side.

**Comment by ankita-04** [comment]
For light theme:
image

For Dark theme:
image

@DhairyaBahl Here is my piece of work.

**Comment by DhairyaBahl** [comment]
@ankita-04 
everything seems to be perfect and I am merging this PR 😄

**Comment by DhairyaBahl** [comment]
@ankita-04 Thanks for the contribution ! Do check out other issues as well.

**Pull request merged**
