### PR TITLE
Disabled empty messages

### LINKED ISSUE #99: Disable empty messages
Currently, we can send empty messages in this app.  We need to disable it
image

### PR DESCRIPTION
**Pull request by garvitgupta13**
Closes #99 
Added a print function which disables empty strings to send

### CODE REVIEW

**Review by DhairyaBahl — CHANGES_REQUESTED** [review]
Add screenshots for all the changes you made where I can see how was it earlier and how is it now !

**Comment by garvitgupta13** [comment]
> Add screenshots for all the changes you made where I can see how was it earlier and how is it now !

Can I attach a video for this. Because now it will not allow empty messages which can be seen in a short video

**Comment by garvitgupta13** [comment]
Please add the necessary gssoc21 labels

**Comment by garvitgupta13** [comment]
In earlier version you can see that empty text boxes can come. 
image
But now you can observe in video that even in I try to send empty messages then diables it
[Link to video](https://drive.google.com/file/d/18L32ZLa5yerfTJe8Y-2WNUV743Jaq5Hq/view?usp=sharing)

**Comment by DhairyaBahl** [comment]
Thank You for the contribution ! Do check out other issues as well !

**Comment by garvitgupta13** [comment]
Hey, @DhairyaBahl  please add the gssoc21 labels before merging PR

**Comment by DhairyaBahl** [comment]
@garvitgupta13 thanks for mentioning the same ! It doesn't matter if we add the labels before or after the submission of PR ! You will get proper points for the same !

**Pull request merged**
