### PR TITLE
added react-flip-move-animation

### LINKED ISSUE #535: Soothing Flipping card animation for messages sent
Whenever you click on send icon, the messages box will perform soothing animation.

### PR DESCRIPTION
**Pull request by anjali1102**
Added React Flip Move helps in animate messages.

gif

### CODE REVIEW

**Comment by anjali1102** [comment]
Yes

**Comment by abhijeet007rocks8** [comment]
Please mention issue number and resolve merge conflict

**Comment by anjali1102** [comment]
Hey, @abhijeet007rocks8 this PR is done for issue number is #535

**Comment by abhijeet-chatterjee** [comment]
@anjali1102 Please resolve the merge conflict so that I can merge the PR

**Pull request closed without merging**
