### PR TITLE
(discard this)Issue#81

### PR DESCRIPTION
**Pull request by Himika-Mishra**
Will be sending a new PR.

### CODE REVIEW

**Comment by DhairyaBahl** [comment]
@Himika-Mishra Shall I close this PR ?

**Comment by Himika-Mishra** [comment]
No no i am kinda having some problem while making a PR so i am resolving it
.

I have successfully completed it . It is just i m pulling a request now.

**Comment by DhairyaBahl** [comment]
@Himika-Mishra Okay Do tag me if the issue is resolved !

**Comment by Himika-Mishra** [comment]
Hi Dhairya,

Yeah I have done it .
Please merge #81 then #82 and then #68 issue.
I have done the changes in this order.

Kindly check and do merge them in this order.

Thanks
Himika Mishra

**Review by DhairyaBahl — COMMENTED** [review]
@Himika-Mishra What is this PR ?

**Comment by Himika-Mishra** [comment]
Its nothing .... Sorry it didnt get there in time but please discard this
request.

Thanks
Himika Mishra

**Comment by abhijeet007rocks8** [comment]
@DhairyaBahl is the PR active or we should close it??

**Comment by DhairyaBahl** [comment]
@abhijeet007rocks8 She mistakenly opened this PR for experimental purposes. I am closing it.

**Pull request closed without merging**
