### PR TITLE
Contactform backend

### PR DESCRIPTION
**Pull request by akshay1027**
Partial fix of #132

Contact form Frontend made. Fully responsive, clean UI, with simple validation, name, subject, email address and text area fields, submit button.

screenshots:  

sending HTTP request using email js:  

  
  
mail received:

### CODE REVIEW

**Comment by akshay1027** [comment]
@DhairyaBahl let me know if this is okay, if so then I will do the email js prior setup for you! maybe you can create a different mail id only for this!

**Comment by akshay1027** [comment]
The emailjs setup is same as in this article( https://medium.com/weekly-webtips/simple-react-contact-form-without-back-end-9fa06eff52d9 )

**Comment by abhijeet007rocks8** [comment]
@akshay1027 why its partial fix can you specify the features that are left

**Comment by akshay1027** [comment]
any update on this @DhairyaBahl ? if the email js setup is done we can merge this right. please let me know

**Pull request merged**
