### PR TITLE
handled dropdown of cards by using custom function

### PR DESCRIPTION
**Pull request by akshay1027**
handled dropdown of cards by creating and using a custom function. Searched online and learnt this method to automatically close a dropdown when another dropdown is opened.

video to show this awesome effect:

https://drive.google.com/file/d/1nG9zXpWD52HlZnI8pPebXud6cDqIfoPN/view?usp=sharing

### CODE REVIEW

**Comment by akshay1027** [comment]
YES

**Comment by akshay1027** [comment]
@DhairyaBahl @abhijeet007rocks8 please let me know

**Comment by abhijeet007rocks8** [comment]
Mention issue number please so that i can add label

**Comment by akshay1027** [comment]
#232 i have mentioned about this over here! @abhijeet007rocks8 @DhairyaBahl

**Comment by akshay1027** [comment]
i have made an issue now, sorry I started without making one #250

**Review by abhijeet007rocks8 — APPROVED** [review]
From next time Please make the issue first before working 
Else it may cause complications later.

Rest is all good

**Comment by akshay1027** [comment]
Sure! Please add labels as well.

**Comment by akshay1027** [comment]
@abhijeet007rocks8

**Pull request merged**
